export enum TypeSender {
  EMAIL = 'EMAIL',
  SMS = 'SMS',
}

export enum ContentRequestOTP {
  VERIFY_OTP = 'VERIFY_OTP',
  RESET_PASSWORD = 'RESET_PASSWORD',
  VERIFY_PHONE_NUMBER = 'VERIFY_PHONE_NUMBER',
  VERIFY_EMAIL = 'VERIFY_EMAIL',
  CREATE_USERS = 'CREATE_USERS',
  DELETE_ACCOUNT = 'DELETE_ACCOUNT',
}
